server:
  port:

spring:
  application:
    name: consultation
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    hikari:
      minimumIdle: 5
      maximumPollSize: 20
      idleTimeout: 30000
      pollName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

springdoc:
  swagger-ui:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

